feat: 아이콘 컴포넌트 추가, 아이콘 svg 파일 최적화 수정
ds92ko/unit-mate pull request #12
Opened 2024-01-08 22:49 UTC by JinEunju

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [x] 기능 변경/추가/삭제
- [ ] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🔗 이슈 링크

관련 Issue가 있을 경우 작성해주세요.

- #2 

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

- 아이콘 컴포넌트 추가

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [x] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [x] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [x] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [x] Warning 혹은 Error가 남아있지 않나요?
- [x] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-09 03:13 UTC, rlacodud approved these changes

2024-01-09 03:13 UTC, rlacodud commented on src/components/Icon/index.css.ts
@JinEunju 빈 파일은 왜 있는건가용?!!!!!! 필요할 때 생성하는 게 좋을 것 같습니다.

2024-01-09 03:13 UTC, rlacodud commented on src/components/Icon/index.tsx
> +      fill={color}
@JinEunju color가 필수값이 아닌 것 같은데 fill에 늘 설정되도록 하면 값을 넘겨받지 않았을 때에도 들어갈 것 같아
이를 고려한 코드로 개선되면 좋을 것 같습니다.

2024-01-09 03:13 UTC, rlacodud commented
리뷰 완료했습니다!

2024-01-10 04:13 UTC, ds92ko requested changes
@JinEunju 리뷰 완료했습니다

2024-01-10 04:13 UTC, ds92ko commented on src/assets/images/icons/bookmark_dark.svg
@JinEunju svg 파일은 사용하지 않으므로 삭제해 주세요

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/constants.ts
> +// eslint-disable-next-line @typescript-eslint/naming-convention
@JinEunju eslint 규칙 무시하는 주석 사용하지 말아주세요! 직접 해결합시다!

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/constants.ts
> +// eslint-disable-next-line @typescript-eslint/naming-convention
@JinEunju eslint 규칙 무시하는 주석 사용하지 말아주세요! 직접 해결합시다!

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/constants.ts
> +export { IconSet };
@JinEunju export 방식 통일성 있게 갑시다

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/constants.ts
> +};
@JinEunju `icon`이라고만 작명해 두면 나중에 어떤 값들을 가지고 있는지 유추하기 어려울 것 같습니다

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.css.ts
@JinEunju 동감입니다! 전에 PR에도 빈파일 그대로 올렸던 것 같은데, PR 올리기 전에 꼭꼭 확인 부탁드릴게요

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.tsx
> +  // eslint-disable-next-line react/require-default-props
@JinEunju eslint 규칙 무시하는 주석 사용하지 말아주세요! 직접 해결합시다! 모르면 검색하기...!

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.tsx
> +// icon.tsx
@JinEunju 불필요한 주석이자 해당 파일명과도 다릅니다. 어디선가 긁어온 복붙 코드를 수정도 안하고 올리셨네요. 이런 코드를 올리다니.. 증말 혼나야대

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/constants.ts
> +export type iconName = 'bookmark' | 'color' | 'mode';
@JinEunju type은 파스칼 케이스를 따릅시다

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.tsx
> +import { iconName, IconSet } from './constants';
@JinEunju type은 파스칼 케이스를 따릅시다

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.tsx
> +  color?: string;
@JinEunju color prop은 왜 옵셔널로 지정했나요? 옵셔널로 할거면 기본값 박아줘야죠

2024-01-10 04:13 UTC, ds92ko commented on src/components/Icon/index.tsx
> +function Icon({ icon, width, height, color }: IconProps) {
@JinEunju Icon 컴포넌트와 icon 프롭스 이름 겹칩니다! 조금만 더 고민하고 작명하기

2024-01-12 11:32 UTC, ds92ko requested changes
@JinEunju 리뷰 완료했습니다. 확인 부탁드립니다.

2024-01-12 11:32 UTC, ds92ko commented on src/components/Icon/index.tsx
> +function Bookmark({ width, height, fillColor }: IconProps) {
@JinEunju 채영주임님이 작업한 컴포넌트와 이름이 겹칩니다..!
이렇게 작업할거면 컴포넌트 이름을 `BookmarkIcon`이라고 조금더 명확하게 명명할 수 있지 않았을까요

2024-01-12 11:32 UTC, ds92ko commented on src/components/Icon/index.tsx
@JinEunju `Icon` 컴포넌트에서 svg 아이콘들을 전부 관리할 수 있도록 요청했던 것 같은데.. 이게 최선인가요 ㅠㅠ

2024-01-12 11:32 UTC, ds92ko commented on src/components/Icon/index.tsx
> +export { Bookmark, ColorPicker, ColorMode };
@JinEunju Icon 컴포넌트 하나만 export 할 수 있도록 구조 다시 바꿔주세요

2024-01-12 11:32 UTC, ds92ko commented on src/pages/Basic/index.tsx
> +      />
@JinEunju 테스트 코드는 올리지 마세요~ PR 올릴때는 해당 컴포넌트가 사용되는 곳에 적용해주세요

2024-01-12 12:46 UTC, JinEunju commented on src/components/Icon/index.tsx
> +  color?: string;
허걱 수정하겠습니다

2024-01-12 12:46 UTC, JinEunju commented on src/components/Icon/index.tsx
> +// icon.tsx
ಥ_ಥ

2024-01-12 12:47 UTC, JinEunju commented on src/components/Icon/index.css.ts
네넵 ಥ_ಥ

2024-01-12 12:48 UTC, closed without merging