feat: history 컴포넌트 생성
ds92ko/unit-mate pull request #23
Opened 2024-01-14 09:16 UTC by rlacodud

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [X] 기능 변경/추가/삭제
- [X] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🔗 이슈 링크

관련 Issue가 있을 경우 작성해주세요.

- #

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

- History component 생성
- 북마크 토글 기능 구현

<br/>

## 💡 특이 사항

PR에 참고할만한 사항이 있을 경우 작성해주세요.

- 계산 시 추가되는 데이터 구조 확인 후 그에 맞춰 수정 필요

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [X] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [X] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [X] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [X] Warning 혹은 Error가 남아있지 않나요?
- [X] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-14 14:27 UTC, JinEunju approved these changes
리뷰 완료 하였습니다 !

2024-01-14 14:50 UTC, ds92ko requested changes
@rlacodud 리뷰 완료했습니다

2024-01-14 14:50 UTC, ds92ko commented on src/components/Bookmark/index.css.ts
> +    '& + &': {
@rlacodud :not(:first-of-type)을 사용하는 편이 더 직관적인 것 같습니다

2024-01-14 14:50 UTC, ds92ko commented on src/components/Bookmark/index.tsx
> +  }, []);
@rlacodud zustand에서 persist 미들웨어 사용하면 직접 storage를 건드리지 않고 zustand만을 이용해서 storage에 값을 저장할 수 있습니다. 만약 직접 storage를 건드릴 거면 zustand 사용이 불필요 하다고 생각됩니다.

2024-01-14 14:50 UTC, ds92ko commented on src/stores/historyStore.ts
> +      ]
@rlacodud 이 데이터는 테스트를 위한 데이터인가요?

2024-01-14 14:50 UTC, ds92ko commented on src/components/Bookmark/index.tsx
> +                  key={`${id}_bookmark`}
@rlacodud id값 자체가 고유하다면 굳이 _bookmark를 붙일 필요는 없어보이는데, _bookmark 를 추가한 이유 알 수 있을까요

2024-01-14 14:50 UTC, ds92ko commented on src/components/History/index.tsx
> +          className={`${historyBookmark} ${isBookmark && 'isActive'}`}
@rlacodud 이 부분 isBookmark가 아닐 때 false 나 undefined 가 클래스명에 들어가지 않나요?

2024-01-14 14:50 UTC, ds92ko commented on src/stores/historyStore.ts
> +  activeTab: 'Basic',
@rlacodud 북마크나 히스토리 데이터와 activeTab 데이터를 분리하지 않은 이유가 있나요?

2024-01-14 14:50 UTC, ds92ko commented on src/pages/Basic/index.tsx
> +  return <Main data={historyData[0].data} />;
@rlacodud index보다는 key로 접근할 수 있도록 데이터 구조를 배열이 아닌 객체로 변경하는건 어떨까요

2024-01-14 15:38 UTC, merged

2024-01-15 08:24 UTC, rlacodud commented on src/stores/historyStore.ts
> +      ]
@ds92ko  넹 테스트를 위해 임시로 생성했습니다!

2024-01-15 08:25 UTC, rlacodud commented on src/components/Bookmark/index.tsx
> +                  key={`${id}_bookmark`}
@ds92ko 작업 당시에는 그저 id로만 넣었을 때에도 console에 key값으로 고유한 값을 설정하라고 하여 수정했었습니다.
한번 더 확인해보겠습니다!