feat: 아이콘 컴포넌트 리팩토링 및 theme nav 적용
ds92ko/unit-mate pull request #28
Opened 2024-01-14 17:43 UTC by ds92ko

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [x] 기능 변경/추가/삭제
- [x] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [x] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

- 아이콘 컴포넌트 리팩토링
- 아이콘 컴포넌트 color props 추가
- theme nav에 아이콘 컴포넌트 적용

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [x] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [x] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [x] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [x] Warning 혹은 Error가 남아있지 않나요?
- [x] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-14 17:44 UTC, ds92ko commented on src/components/Icon/index.tsx
>      </svg>
기존에 복잡했던 SVG 태그 구조 간소화 했습니다

2024-01-14 17:44 UTC, ds92ko commented on src/components/Icon/index.tsx
> +      viewBox="0 0 36 36"
통일할 수 있는 속성은 통일해서 관리할 속성을 줄였습니다

2024-01-14 17:45 UTC, ds92ko commented on src/components/Icon/index.tsx
> +  size: number;
너비와 높이를 항상 같게 해 사이즈 하나로 너비와 높이를 관리할 수 있도록 하였습니다

2024-01-14 17:46 UTC, ds92ko commented on src/components/Icon/constants.tsx
> +  clipRule: 'evenodd' | 'nonzero';
옵셔널로 되어있었지만 기본값이 없어서 필수로 변경하였습니다

2024-01-14 17:48 UTC, ds92ko commented on src/styles/global.css.ts
> +});
버튼 글로벌 스타일 추가하였습니다

2024-01-15 03:23 UTC, rlacodud approved these changes
리뷰 완료했습니다!

2024-01-15 03:23 UTC, rlacodud commented on src/components/Icon/index.tsx
> +  size: number;
@ds92ko 제가 로직을 잘못 이해한걸 수도 있는데 에러 페이지에 사용되는 아이콘의 경우, 비율이 1:1이 아니어서 해당 방식으로 적용했을 때 우려됩니다!

2024-01-15 10:26 UTC, JinEunju commented on src/components/Icon/index.tsx
> +  size: number;
@ds92ko 테마 아이콘도 width와 height가 다른게 있어서 따로 분리 하였었습니다 !

2024-01-15 10:27 UTC, JinEunju requested changes
리뷰 완료 하였습니다 !

2024-01-15 15:28 UTC, JinEunju approved these changes
리뷰 완료 하였습니다 !

2024-01-16 10:34 UTC, merged