feat: input 컴포넌트 제작
ds92ko/unit-mate pull request #34
Opened 2024-01-18 16:41 UTC by rlacodud

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [X] 기능 변경/추가/삭제
- [X] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🔗 이슈 링크

관련 Issue가 있을 경우 작성해주세요.

- #

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

- Input component 추가
- 에러 페이지 아이콘 적용

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [X] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [X] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [X] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [X] Warning 혹은 Error가 남아있지 않나요?
- [X] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-19 12:44 UTC, ds92ko requested changes
@rlacodud 리뷰 완료하였습니다

2024-01-19 12:44 UTC, ds92ko commented on src/components/GuideInfo/type.tsx
> +  icon: string;
@rlacodud icon 데이터 타입 string 말고 IconName으로 바꿔주세요

2024-01-19 12:44 UTC, ds92ko commented on src/styles/layout.css.ts
> +  maxHeight: 'calc(100% - 150px)',
@rlacodud 150은 무슨 숫자인가요?

2024-01-20 04:36 UTC, JinEunju approved these changes
리뷰 완료 하였습니다 !

2024-01-20 07:00 UTC, closed without merging