feat: og이미지, 파비콘, 디스크립션 추가
ds92ko/unit-mate pull request #35
Opened 2024-01-18 22:25 UTC by JinEunju

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [ ] 기능 변경/추가/삭제
- [ ] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [x] 기타 (설명: og이미지, 파비콘, 디스크립션 추가)

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

-  og이미지, 파비콘, 디스크립션 추가

<br/>

## 💡 특이 사항

PR에 참고할만한 사항이 있을 경우 작성해주세요.

- 파비콘 svg 사이즈: 48 * 48
- og png 사이즈 : 800 * 400

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [x] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [x] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [x] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [x] Warning 혹은 Error가 남아있지 않나요?
- [x] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-19 12:36 UTC, ds92ko requested changes
@JinEunju 리뷰 완료하였습니다

2024-01-19 12:36 UTC, ds92ko commented on index.html
> +    />
@JinEunju 아래 OG 속성도 같이 추가해주세요
og:type, og:url, og:site_name, og:locale, og:image:width, og:image:height

2024-01-19 12:36 UTC, ds92ko commented on public/img_og.png
@JinEunju 확장자 JPG로 해주세요

2024-01-19 12:36 UTC, ds92ko commented on index.html
> +    />
@JinEunju keywords 정도는 추가 할까요?

2024-01-20 07:04 UTC, rlacodud approved these changes
확인 완료했습니다!

2024-01-20 12:13 UTC, merged