feat: backspace 키보드 기능 추가
ds92ko/unit-mate pull request #70
Opened 2024-02-19 14:10 UTC by JinEunju

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [x] 기능 변경/추가/삭제
- [ ] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🔗 이슈 링크

관련 Issue가 있을 경우 작성해주세요.

- #65 

<br/>

## 🛠️ 작업 내용

`required` 작업 내용에 대해 작성해주세요.

-백스페이스 키 누르면 1글자씩 지워지는 기능 추가

<br/>

## 💡 특이 사항

PR에 참고할만한 사항이 있을 경우 작성해주세요.

-keyboard 함수를 useEffect 밖에 정의하였을때, 해당 함수는 useEffect의 의존성 배열에 포함되지 않아서 ESLint 경고가 발생하는  이슈가 있었습니다. 함수를 useEffect 내부에 정의하면 매 렌더링마다 함수가 재생성되므로 성능에 영향을 줄 수 있지만  ESLint 경고를 해결할 수 있었습니다.

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [x] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [x] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [x] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [x] Warning 혹은 Error가 남아있지 않나요?
- [x] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-02-19 15:48 UTC, ds92ko requested changes
@JinEunju 리뷰 완료했습니다!

2024-02-19 15:48 UTC, ds92ko commented on src/components/Keyboard/index.tsx
> +      }
@JinEunju 다른 키는 전부 keyUp에 달려있는데 backspace만 keyDown에 적용한 이유가 있나요?

2024-02-19 15:48 UTC, ds92ko commented on src/components/Keyboard/index.tsx
> +  }, [backspaceCalcValue, buttonRefs, key]);
@JinEunju 의존성 배열에 buttonRefs는 빠져도 되지 않나요?

2024-02-19 15:48 UTC, ds92ko commented on src/stores/calcStore.ts
> +
@JinEunju 여기 빈 줄 들어가있어요

2024-02-20 08:01 UTC, rlacodud approved these changes
리뷰 완료했습니다!

2024-02-20 12:53 UTC, merged