feat: Layout 작업
ds92ko/unit-mate pull request #8
Opened 2024-01-04 14:23 UTC by rlacodud

## 📋 PR 타입

`required` 해당되는 PR 타입을 하나 이상 체크하세요.

- [ ] 기능 변경/추가/삭제
- [X] UI 변경/추가/삭제
- [ ] 주석 변경/추가/삭제
- [ ] 문서 변경/추가/삭제
- [ ] 파일명 또는 폴더명 수정/삭제
- [ ] 버그 수정
- [ ] 코드 리팩토링 (기능 변경 ❌, API 변경 ❌)
- [ ] 패키지 매니저 및 빌드 관련 변경
- [ ] 기타 (설명: )

<br/>

## 🛠️ 작업 내용

- react-router-dom 설치
- 라우터 설정
- UI layout 작업

<br/>

## 💡 특이 사항

어느정도 반응형은 되어야 할 것 같아 rem으로 작업할지 고민 중입니다.

<br/>

## ✅ 체크 리스트

`required` PR이 다음 요구 사항을 충족하는지 체크하세요.

- [X] 변경/추가/제거 사항에 대해 충분한 테스트가 이루어졌나요?
- [X] 변경/추가/제거 사항으로 인한 사이드 이펙트가 발생하지 않나요?
- [X] 변경/추가/제거 사항에 대해 주석이나 설명이 필요한 부분이 있는지 확인했나요?
- [X] Warning 혹은 Error가 남아있지 않나요?
- [X] 불필요한 log나 디버깅 코드는 제거되었나요?

<br/>

2024-01-04 17:47 UTC, ds92ko requested changes
@rlacodud 리뷰 완료했습니다

2024-01-06 04:15 UTC, JinEunju approved these changes
리뷰 완료 했습니다

2024-01-06 04:15 UTC, JinEunju commented on src/style/layout.css
css작성 할때 중요한 순서부터 작성하면 좋을 것 같습니다

2024-01-06 04:50 UTC, rlacodud commented
리뷰 확인했습니다!

2024-01-06 04:50 UTC, closed without merging